### ISSUE TITLE
Issue Edit bibliography

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/GitTest#3]
As I am testing your new DEPiCTed Version at the moment, I will send you one of the issues I recognised (But of course you will receive an email with all the detailed descriptions later on)

In the tab Edit bibliography we still have some issues: 
There are still too many fields. You have to delete the 'coordinates of place' and the 'macro region' as they belong to the sociobiographic speaker information. In addition there is still some problem with the source type list as I can see all source types twice or even three times.

Excited to see whether you receive my Issue ;-)

**Comment by magnusnissel** [comment]
Thanks for the heads up. I think you could actually start using the Issue tracking system on the offical DEPiCTED repository for this: https://github.com/magnusnissel/DEPiCTed/issues

Closing this (and tagging as invalid and wontfix for fun :smile: )
